server:
  port: 8080

spring:
  application:
    name: e-requisition

cassandra:
  contact-points: localhost
  keyspace-name: requisition
  port: 9042

ocds:
  prefixes:
    main: ocds-t1s2t3
    test: test-t1s2t3

uri:
  tender: http://dev.public.eprocurement.systems/tenders